export const allTexts = {
  error: "error",
  defualtText: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum`,
  conform_del: "Confirm Delete",
  delete_msg: "Are you sure you want to delete this post?",
  cancel: "Cancel",
  delete: "Delete",
  do_not_have_account: `Don't have an account?`,
  register: "Register",
  password: "Password",
  username: "UserName",
  login: "Login",
  username_is_required: "Username is required",
  password_is_required: "Password is required",
  invalid_email: "Invalid email",
  email_is_required: "Email is required",
  image_is_required: "Image is required",
  user: "user",
  there_is_not_archive_post: "there is not archive post",
  archive: "Archive",
  deliver: "Deliver",
  image: "Image",
  email: "Email",
  feed: "Feed",
  chat: "Chat",
  totalMessage: "TotalMessage",
  logout: "Logout",
  hello:"Hello",
  start_chat_and_select_a_user:"Select a user and Start chat! "
};
